### ISSUE TITLE
Needs work

### ISSUE THREAD

**Issue by axeberg** [chas-academy/08-weather-app-jennifersoderberg#1]
@jennifersoderberg  make sure to ping me when you close this issue to indicate that this has been deployed and is ready for grading.

**Comment by jennifersoderberg** [comment]
Repo: https://github.com/jennifersoderberg/08-weather-app
Deployed version: https://weather-app.jennifersoderberg.now.sh/

@axelolsson

**Comment by axeberg** [comment]
@jennifersoderberg please stop creating repos outside of the hand-in format!

Furthermore you need to implement a fallback when the user clicks "Block" when the app asks for geolocation access.

**Comment by jennifersoderberg** [comment]
@axelolsson Finished implementing fallback for when user denies geolocation access. 

Repo: https://github.com/jennifersoderberg/08-weather-app
Deployed version: https://weather-app.jennifersoderberg.now.sh/

(you gave me permission to create a new repo)
